### ISSUE TITLE
Generated rules file should warn that it is automatically created

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [os-climate/osc-trino-acl-dsl#7]
The generated rules file should contain a comment that it is automatically created from a source file, and that changes should be made to that source (yml) file, not rules.json.

**Comment by erikerlandson** [comment]
unfortunately, json doesn't allow comments. it's one of the reasons I made the DSL yaml, so humans could add comments to it

**Comment by erikerlandson** [comment]
I wrote a dsl pre-commit check that will detect when they are out of sync and fail with instructions, but it assumes you can get the pre-commit checks working.  that check is what is failing in the CI on github

**Comment by MichaelTiemannOSC** [comment]
Aha.  I feel like I'm really close, and I did fix my env so I should be able to get all the way.  Looks like I need to add a newline at the end of the file...
